name: "Get changed files list"
description: "Setup Node with caching for dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install platform
      run: |
        arduino-cli core update-index
        arduino-cli core install ${{ env.platform }}
      shell: bash

    - name: Install popular libs
      run: |
        arduino-cli lib install LiquidCrystal
      shell: bash