[wokwi]
version = 1
firmware = 'build/mc_lab_01.ino.hex' 
elf = 'build/mc_lab_01.ino.elf'

[lab_setup]
led_delay = "800ms"
btn1 = "btn1"
P0 = "led8"
P1 = "led6"
P2 = "led7"
P3 = "led1"
P4 = "led5"
P5 = "led4"
P6 = "led3"
P7 = "led2"
