name: Cheking of compile Arduino sketch for AVR/AtMega and ESP8266

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-matrix:
    strategy:
      matrix:
        arduino-platform:
          - "arduino:avr"
          - "esp8266:esp8266"
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:mega"
          - arduino-platform: "esp8266:esp8266"
            fqbn: "esp8266:esp8266:generic"

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./mc_labs/mc_lab_01/*.ino
